---
title: 'Final Review Sheet'
output: html_document
---

## Final Review Sheet

We made it!

I am quite proud of all of you for making it to this point. This was never an easy class, and it should not be. This class is designed to show you the basic concepts that underlie all of psychological analyses. Whether you go on to be clinical psychologists or in an entirely unrelated field, I hope that you will take away an understanding, and an appreciation for the science that floods the news daily. Being able to understand what all those numbers mean will make you a better consumer of scientific knowledge.

### OK, on to what you really want in a review sheet...

We have learned three different kinds of ANOVA in this class.

#### 1. One-Way Between Subjects ANOVA

`aov(DV~IV)`

-   DV is what is being measured, usually a score, rating, measurement, etc.

-   IV is what is being manipulated, in order for `R` to calculate anything, this **must** be a factor.

-   `factor(variable)` - This will produce the variable as a factor.

-   This produces **One F**

#### 2. One-Way Between Subjects ANOVA

`aov(DV~IV1*IV2)`

-   DV is what is being measured, usually a score, rating, measurement, etc.

-   IV1 is what is being manipulated: Control, Treatment, Treatment 2, etc.

-   IV2 is also what is being manipulated **throughout** the IV1.

    -   Control-High, Control-Medium, Control-Low

-   This produces **Three F's**

#### 3. One-Way Subjects ANOVA

`aov(DV~IV+Error(Subject))`

-   DV is what is being measured, usually a score, rating, measurement, etc.

-   IV1 is what is being manipulated: Control, Treatment, Treatment 2, etc.

-   Subject is the ID of the participant taking the experiment, they factor into your analysis because their data is in each level of the independent variable. **Must be a factor**.

-   This produces **One F**.

#### 4. Non-Parametric Tests

#### Independent 2-group Mann-Whitney U Test

`wilcox.test(y~A)`

-   where y is numeric

-   A is A binary factor (0,1) \| (yes, no)

#### Independent 2-group Mann-Whitney U Test

`wilcox.test(y,x)` \#

-   y is numeric x is numeric

#### Dependent 2-group Wilcoxon Signed Rank Test

`wilcox.test(y1,y2,paired=TRUE)`

-   Where y1 and y2 are numeric

#### Kruskal Wallis Test One Way Anova by Ranks

`kruskal.test(y~A)`

-   Where y1 is numeric and A is a factor

#### Friedman Test

`friedman.test(y~A|B)`

-   y is data values

-   A is a grouping factor

-   B is a blocking factor
